### ISSUE TITLE
WikiText-103

### ISSUE THREAD

**Issue by Cortexelus** [HazyResearch/state-spaces#1]
Hi, I'm interested in recreating your WikiText-103 LM experiment. Is it possible you could make that easier for me? Thanks! CJ

**Comment by yuvalkirstain** [comment]
Can you please provide instructions to reproduce the WikiText-103 results?
When running `python train.py wandb=null experiment=s4-wt103` I get an exception that seems to be related to the cutoff values:
```
Traceback (most recent call last):
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/olab/kirstain/state-spaces/train.py", line 525, in main
    train(config)
  File "/home/olab/kirstain/state-spaces/train.py", line 463, in train
    trainer.fit(model)
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1132, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1432, in _call_setup_hook
    self.call_hook("setup", stage=fn)
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1483, in call_hook
    output = model_fx(*args, **kwargs)
  File "/home/olab/kirstain/state-spaces/train.py", line 71, in setup
    self.task = task = utils.instantiate(
  File "/home/olab/kirstain/state-spaces/src/utils/config.py", line 99, in instantiate
    return obj()
  File "/home/olab/kirstain/state-spaces/src/tasks/tasks.py", line 171, in __init__
    encoder = U.TupleModule(AdaptiveEmbedding)(
  File "/home/olab/kirstain/state-spaces/src/models/nn/adaptive_softmax.py", line 273, in __init__
    self.emb_layers.append(nn.Embedding(r_idx - l_idx, d_emb_i))
  File "/home/olab/kirstain/anaconda3/envs/state-spaces/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 139, in __init__
    self.weight = Parameter(torch.empty((num_embeddings, embedding_dim), **factory_kwargs))
RuntimeError: Trying to create tensor with negative dimension -166719: [-166719, 16]
```

**Comment by albertfgu** [comment]
Hi, the WikiText-103 LM config has been added to the README. It can be run with
```
python -m train experiment=s4-wt103 wandb=null
```
Note that these experiments are quite expensive. We used 8 A100 GPUs and trained for around 5 days (according to the original paper, the baseline Transformer used 3 days). This is because the S4 model overfits harder on this small dataset, so we turned up the regularization very high and trained for longer.

**Comment by thanhlt998** [comment]
> Hi, the WikiText-103 LM config has been added to the README. It can be run with
> 
> ```
> python -m train experiment=s4-wt103 wandb=null
> ```
> 
> Note that these experiments are quite expensive. We used 8 A100 GPUs and trained for around 5 days (according to the original paper, the baseline Transformer used 3 days). This is because the S4 model overfits harder on this small dataset, so we turned up the regularization very high and trained for longer.

Could you provide me your pretrained S4 LM on the wikitext-103 corpus to experiment the power of this architecture on other downstream tasks? Thanks!

**Comment by yuvalkirstain** [comment]
@albertfgu Thanks for the config update. 

Can you please upload the logs from the Wikitext-103 experiment? It will help a lot in reproducing the results and provide an early signal if something is wrong. 
I am trying to reproduce the results and after 23,000 steps the validation perplexity is ~29 (I expected a lower perplexity at this stage).

Thank you very much!

**Comment by albertfgu** [comment]
Hi @yuvalkirstain, I am working on exporting the logs. It is a bit complicated because this experiment was split into multiple runs with checkpointing/resuming because of resource management on our cluster.

That said, your perplexity after 23000 steps actually tracks ours very closely. As noted in the paper, S4 had tendencies to overfit on this dataset, so we used very high regularization that slowed down training speed.

**Comment by gaceladri** [comment]
Hello, @albertfgu are you planning to release your pre-trained models for text? I am very interested on them. Also, are you planing to integrate your models in Huggingface? https://github.com/huggingface/transformers/pull/14837

**Comment by albertfgu** [comment]
I think we are leaning toward not releasing the one trained for the paper because of a few reasons, such as the model implementation still undergoing changes and improvements. We are working with HuggingFace to release a version of the model though.

**Comment by albertfgu** [comment]
A WikiText-103 model has been re-trained and released. Instructions for using it are located throughout the READMEs, for example [here](https://github.com/HazyResearch/state-spaces#example-1-language).
