### ISSUE TITLE
Can't run the code; OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by koseoyoung** [HazyResearch/state-spaces#108]
Hi, I'm following the README to run the code on GPU machine. 
After installing all packages mentioned, I tried to run the train sample code, but having 
`OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory` error. 
Am I doing something wrong? Thank you for your help!   

```
(s4) [sko1@bridges2-login011 state-spaces]$ python -m train pipeline=mnist model=s4
/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ocean/projects/cis230033p/sko1/state-spaces/train.py", line 23, in <module>
    from src.dataloaders import SequenceDataset  # TODO make registry
  File "/ocean/projects/cis230033p/sko1/state-spaces/src/dataloaders/__init__.py", line 1, in <module>
    from . import audio, basic, et, lm, lra, synthetic, ts, vision
  File "/ocean/projects/cis230033p/sko1/state-spaces/src/dataloaders/audio.py", line 8, in <module>
    import torchaudio
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchaudio/_extension.py", line 135, in <module>
    _init_extension()
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchaudio/_extension.py", line 105, in _init_extension
    _load_lib("libtorchaudio")
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchaudio/_extension.py", line 52, in _load_lib
    torch.ops.load_library(path)
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```

**Comment by albertfgu** [comment]
This often happens with mismatched library versions. What are your versions of the main torch libraries? (e.g. output of `conda/pip list | grep torch`)
Make sure to follow the instructions on the pytorch website when installing the packages.

**Comment by albertfgu** [comment]
Your torchaudio version is out of date. In general the torchaudio version and torchvision minor versions should match (0.14 for pytorch 2.0) and the torchtext version is one higher. I'm not sure how you installed them; if using pip, you can try upgrading with `pip install -U torchaudio`

**Comment by koseoyoung** [comment]
@albertfgu Great, thanks! Now the package is exactly the same as README (torchtext is 0.15.2) 
```
(s4) [sko1@v007 state-spaces]$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
pytorch                   1.13.1          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-lightning         1.9.3                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
torch                     2.0.1                    pypi_0    pypi
torchaudio                0.13.1               py39_cu116    pytorch
torchdata                 0.6.1                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchtext                 0.15.2                   pypi_0    pypi
torchvision               0.14.1               py39_cu116    pytorch
```

Now `python example.py` works, but training still has some OSError. Do you know what am I missing with these packages?

```
(s4) [sko1@v007 state-spaces]$ python -m train experiment=forecasting/s4-informer-etth
Traceback (most recent call last):
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ocean/projects/cis230033p/sko1/state-spaces/train.py", line 23, in <module>
    from src.dataloaders import SequenceDataset  # TODO make registry
  File "/ocean/projects/cis230033p/sko1/state-spaces/src/dataloaders/__init__.py", line 1, in <module>
    from . import audio, basic, et, lm, lra, synthetic, ts, vision
  File "/ocean/projects/cis230033p/sko1/state-spaces/src/dataloaders/lra.py", line 12, in <module>
    import torchtext
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchtext/__init__.py", line 6, in <module>
    from torchtext import _extension  # noqa: F401
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchtext/_extension.py", line 64, in <module>
    _init_extension()
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchtext/_extension.py", line 58, in _init_extension
    _load_lib("libtorchtext")
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchtext/_extension.py", line 50, in _load_lib
    torch.ops.load_library(path)
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /ocean/projects/cis230033p/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchtext/lib/libtorchtext.so: undefined symbol: _ZN2at4_ops10select_int4callERKNS_6TensorElN3c106SymIntE
```
Thanks!

**Comment by koseoyoung** [comment]
I tried to fix the `torchtext` version since it seems like Pytorch 1.13.0 requires torchtext 0.14.0., and it requires torch to be 1.13.0 as well. However, it seems like torchdata 0.6.1 requires torch==2.0.1, but I have torch 1.13.1 which is incompatible. 

Anyway, still having another issue. 

```
(s4) [sko1@v007 state-spaces]$ python -m train experiment=forecasting/s4-informer-etth
Traceback (most recent call last):
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ocean/projects/cis230033p/sko1/state-spaces/train.py", line 10, in <module>
    import pytorch_lightning as pl
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/functional/audio/__init__.py", line 14, in <module>
    from torchmetrics.functional.audio.pit import permutation_invariant_training, pit_permutate  # noqa: F401
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/functional/audio/pit.py", line 22, in <module>
    from torchmetrics.utilities.imports import _SCIPY_AVAILABLE
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/utilities/__init__.py", line 1, in <module>
    from torchmetrics.utilities.checks import check_forward_full_state_property  # noqa: F401
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/utilities/checks.py", line 25, in <module>
    from torchmetrics.utilities.data import select_topk, to_onehot
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/utilities/data.py", line 19, in <module>
    from torchmetrics.utilities.imports import _TORCH_GREATER_EQUAL_1_12, _XLA_AVAILABLE
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/utilities/imports.py", line 112, in <module>
    _TORCHVISION_GREATER_EQUAL_0_8: Optional[bool] = _compare_version("torchvision", operator.ge, "0.8.0")
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/utilities/imports.py", line 78, in _compare_version
    if not _module_available(package):
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchmetrics/utilities/imports.py", line 59, in _module_available
    module = import_module(module_names[0])
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/datasets/_optical_flow.py", line 11, in <module>
    from ..io.image import _read_png_16
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/io/__init__.py", line 8, in <module>
    from ._load_gpu_decoder import _HAS_GPU_VIDEO_DECODER
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/io/_load_gpu_decoder.py", line 1, in <module>
    from ..extension import _load_library
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/extension.py", line 107, in <module>
    _check_cuda_version()
  File "/jet/home/sko1/.conda/envs/s4/lib/python3.9/site-packages/torchvision/extension.py", line 80, in _check_cuda_version
    raise RuntimeError(
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.6. Please reinstall the torchvision that matches your PyTorch install.
```

```
(s4) [sko1@v007 state-spaces]$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
pytorch                   1.13.1          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
pytorch-lightning         1.9.3                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
torch                     1.13.1                   pypi_0    pypi
torchaudio                0.13.1               py39_cu116    pytorch
torchdata                 0.6.1                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchtext                 0.14.1                   pypi_0    pypi
torchvision               0.14.1               py39_cu116    pytorch
```

**Comment by koseoyoung** [comment]
Hi, I just realized my cuda version is 11.7, so I followed this guide to install the relevant package -- https://pytorch.org/get-started/previous-versions/ 
`conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia`

However, the following issues came out: 
```
(s4-cuda) [sko1@v007 state-spaces]$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
pytorch                   1.13.1          py3.9_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-lightning         1.9.3                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
torch                     2.0.1                    pypi_0    pypi
torchaudio                0.13.1               py39_cu117    pytorch
torchdata                 0.6.1                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchtext                 0.14.1                   pypi_0    pypi
torchvision               0.14.1               py39_cu117    pytorch
```

```
(s4-cuda) [sko1@v007 state-spaces]$ pip install torchtext==0.14.1
Collecting torchtext==0.14.1
  Using cached torchtext-0.14.1-cp39-cp39-manylinux1_x86_64.whl (2.0 MB)
Requirement already satisfied: tqdm in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from torchtext==0.14.1) (4.65.0)
Requirement already satisfied: requests in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from torchtext==0.14.1) (2.29.0)
Requirement already satisfied: torch==1.13.1 in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from torchtext==0.14.1) (1.13.1)
Requirement already satisfied: numpy in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from torchtext==0.14.1) (1.24.3)
Requirement already satisfied: typing_extensions in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from torch==1.13.1->torchtext==0.14.1) (4.6.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from requests->torchtext==0.14.1) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from requests->torchtext==0.14.1) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from requests->torchtext==0.14.1) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /ocean/projects/cis230033p/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages (from requests->torchtext==0.14.1) (2023.5.7)
Installing collected packages: torchtext
  Attempting uninstall: torchtext
    Found existing installation: torchtext 0.15.2
    Uninstalling torchtext-0.15.2:
      Successfully uninstalled torchtext-0.15.2
Successfully installed torchtext-0.14.1
(s4-cuda) [sko1@v007 state-spaces]$ python -m train experiment=forecasting/s4-informer-etth
Traceback (most recent call last):
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/ocean/projects/cis230033p/sko1/state-spaces/train.py", line 23, in <module>
    from src.dataloaders import SequenceDataset  # TODO make registry
  File "/ocean/projects/cis230033p/sko1/state-spaces/src/dataloaders/__init__.py", line 1, in <module>
    from . import audio, basic, et, lm, lra, synthetic, ts, vision
  File "/ocean/projects/cis230033p/sko1/state-spaces/src/dataloaders/lra.py", line 12, in <module>
    import torchtext
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torchtext/__init__.py", line 12, in <module>
    from . import data, datasets, prototype, functional, models, nn, transforms, utils, vocab, experimental
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torchtext/datasets/__init__.py", line 3, in <module>
    from .ag_news import AG_NEWS
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torchtext/datasets/ag_news.py", line 12, in <module>
    from torchdata.datapipes.iter import FileOpener, IterableWrapper
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torchdata/__init__.py", line 9, in <module>
    from . import datapipes
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torchdata/datapipes/__init__.py", line 9, in <module>
    from . import iter, map, utils
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torchdata/datapipes/iter/__init__.py", line 121, in <module>
    from torchdata.datapipes.iter.util.sharding import (
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torchdata/datapipes/iter/util/sharding.py", line 9, in <module>
    from torch.utils.data.datapipes.iter.sharding import SHARDING_PRIORITIES
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torch/utils/data/datapipes/iter/sharding.py", line 29, in <module>
    class ShardingFilterIterDataPipe(_ShardingIterDataPipe):
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torch/utils/data/datapipes/_decorator.py", line 34, in __call__
    IterDataPipe.register_datapipe_as_function(self.name, cls, enable_df_api_tracing=self.enable_df_api_tracing)
  File "/jet/home/sko1/.conda/envs/s4-cuda/lib/python3.9/site-packages/torch/utils/data/datapipes/datapipe.py", line 136, in register_datapipe_as_function
    raise Exception("Unable to add DataPipe function name {} as it is already taken".format(function_name))
Exception: Unable to add DataPipe function name sharding_filter as it is already take
```
Any thoughts to debug this issue?
Also, if I follow the README in order, I think the package is not installed as expected. (I've tried to re-install a few to make the version as expected). Can you try to follow the README to install packages from scratch?

**Comment by albertfgu** [comment]
I haven't seen that issue. Everything looks like package version issues.
The installation example from the README is just meant to be an example, and it's currently out of date. It will run into an issue if used literally because when you `pip install torchtext` (from the requirements.txt) it will install the latest version of torchtext (which is for torch 2.0) and all the dependencies get out of whack.

You should be fine by using the standard installation procedure:
1. Install pytorch from the website instructions
2. Install from the requirements file here

Example for CUDA 11.7:
```
conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.7 -c pytorch -c nvidia
pip install -r requirements.txt
```
(You should do this in a fresh environment)

If that doesn't work - the last time I tried this I ran into conda bugs - you might be able to install everything from pip. Create a fresh environment, add `torch torchvision torchaudio` to the `requirements.txt`, and install all of those at once.
