### ISSUE TITLE
Can't compile the custom cauchy kernel

### ISSUE THREAD

**Issue by IzzetYoung** [HazyResearch/state-spaces#18]
Dear all,
Sorry for a silly question.  I'm having trouble install cauchy kernel by custom cuda kernel.
running `python setup.py install` like this:
```
~/LongSeq/state-spaces/extensions/cauchy$ python setup.py install
running install
~/miniconda3/envs/lightning/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
~/miniconda3/envs/lightning/lib/python3.9/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating cauchy_mult.egg-info
writing cauchy_mult.egg-info/PKG-INFO
writing dependency_links to cauchy_mult.egg-info/dependency_links.txt
writing top-level names to cauchy_mult.egg-info/top_level.txt
writing manifest file 'cauchy_mult.egg-info/SOURCES.txt'
reading manifest file 'cauchy_mult.egg-info/SOURCES.txt'
writing manifest file 'cauchy_mult.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cauchy_mult.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cauchy_mult.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cauchy_mult.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cauchy_mult.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/cauchy_mult-0.0.0-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cauchy_mult-0.0.0-py3.9.egg
Copying cauchy_mult-0.0.0-py3.9.egg to ~/miniconda3/envs/lightning/lib/python3.9/site-packages
Adding cauchy-mult 0.0.0 to easy-install.pth file

Installed ~/miniconda3/envs/lightning/lib/python3.9/site-packages/cauchy_mult-0.0.0-py3.9.egg
Processing dependencies for cauchy-mult==0.0.0
Finished processing dependencies for cauchy-mult==0.0.0
```
but cannot import the `cauchy_mult` when I running `test_cauchy.py`
```
~/LongSeq/state-spaces/extensions/cauchy$ python test_cauchy.py 
Traceback (most recent call last):
  File "~/LongSeq/state-spaces/extensions/cauchy/test_cauchy.py", line 8, in <module>
    from cauchy import cauchy_mult_torch, cauchy_mult_keops, cauchy_mult
  File "~/LongSeq/state-spaces/extensions/cauchy/cauchy.py", line 5, in <module>
    from cauchy_mult import cauchy_mult_fwd, cauchy_mult_bwd, cauchy_mult_sym_fwd, cauchy_mult_sym_bwd
ModuleNotFoundError: No module named 'cauchy_mult'
```
I also try to run `python -m pip install` and change python to 3.8, but they don't work too.

**Comment by albertfgu** [comment]
Were you able to resolve this? I can't reproduce this error with a few different environments.

Aside from the `test_cauchy.py` test script, does the end-to-end code run using the extension? If the code throws an error or you see the warning
```
CUDA extension for cauchy multiplication not found. Install by going to extensions/cauchy/ and running `python setup.py install`. This should speed up end-to-end training by 10-50%
```
then your installation did not work, otherwise it installed correctly.

If it does not work, does the `pykeops` solution work?

**Comment by IzzetYoung** [comment]
I have resolved this issue by reinstall cuda tookit, thank for your response!!

**Comment by tbenst** [comment]
I have the exact same issue as the original poster, on Python 3.10 in my case.

`warning: install_lib: 'build/lib' does not exist -- no Python modules to install` is the operable line.

The issue is that https://github.com/HazyResearch/state-spaces/blob/06dbbdfd0876501a7f12bf3262121badbc7658af/extensions/cauchy/setup.py#L7 does not give an error if CUDA isn’t available / paths aren’t set.

On Sherlock, I had to do:
```
> ml cuda/11.7
> ml gcc
```

and then the install succeeds
