### ISSUE TITLE
load_dataset process getting Killed

### ISSUE THREAD

**Issue by pragyasrivastava0805** [HazyResearch/state-spaces#28]
''' dataset = load_dataset(
            "csv",
            data_files={
                "train": str(self.data_dir / "basic_train.tsv"),
                "val": str(self.data_dir / "basic_val.tsv"),
                "test": str(self.data_dir / "basic_test.tsv"),
            },
            delimiter="\t",
            keep_in_memory=True,
        )''' this piece of code in src/dataloaders/datasets.py is giving error and the dataloading process is aborted

**Comment by albertfgu** [comment]
Which dataset are you using?

**Comment by pragyasrivastava0805** [comment]
This has been sorted now .
But now,I am facing another issue 
Traceback (most recent call last):███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                         | 394/500 [00:00<00:00, 606.73ex/s]
  File "/voyager-volume/state-spaces/train.py", line 548, in main████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 468/500 [00:00<00:00, 648.01ex/s]
    train(config)
  File "/voyager-volume/state-spaces/train.py", line 493, in train
    trainer.fit(model)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 769, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1172, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1492, in _call_setup_hook
    self._call_lightning_module_hook("setup", stage=fn)
  File "/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1593, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/voyager-volume/state-spaces/train.py", line 74, in setup
    self.model = utils.instantiate(registry.model, self.hparams.model)
  File "/voyager-volume/state-spaces/src/utils/config.py", line 99, in instantiate
    return obj()
TypeError: __init__() missing 3 required positional arguments: 'd_input', 'd_output', and 'l_output'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
while using unicornn model and listops dataset

**Comment by pragyasrivastava0805** [comment]
@albertfgu ,could you please help me this issue ASAP.

**Comment by albertfgu** [comment]
Resolved through direct correspondence. Baselines such as unicornn have been updated.

**Comment by Alchemy5** [comment]
How was this resolved, I've been facing the same errors?

**Comment by albertfgu** [comment]
I'm not sure what the resolution was. I was sent a series of confusing emails and then he said it was sorted. It might have been user error.
