### ISSUE TITLE
Error while using DataParrallel 

### ISSUE THREAD

**Issue by AmeenAli** [HazyResearch/state-spaces#34]
Hello,
Thanks for sharing this awesome work, when i try to run example.py i get the following error : 

`CUDA extension for cauchy multiplication not found. Install by going to extensions/cauchy/ and running `python setup.py install`. This should speed up end-to-end training by 10-50%
Falling back on slow Cauchy kernel. Install at least one of pykeops or the CUDA extension for efficiency.
cuda
==> Preparing cifar10 data..
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
==> Building model..
Optimizer group 0 | 28 tensors
0it [00:11, ?it/s]                                                                                                                                    | 0/200 [00:00<?, ?it/s]
Epoch: 0:   0%|                                                                                                                                       | 0/200 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "example.py", line 373, in <module>
    train()
  File "example.py", line 312, in train
    outputs = model(inputs)
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "example.py", line 196, in forward
    z, _ = layer(z)
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data1/ameen/state-spaces/src/models/sequence/ss/standalone/s4.py", line 842, in forward
    k = self.kernel(L=L) # (C H L) (B C H L)
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data1/ameen/state-spaces/src/models/sequence/ss/standalone/s4.py", line 752, in forward
    k = self.kernel(L=L)
  File "/media/data2/ameenali/anaconda3/envs/ameen/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data1/ameen/state-spaces/src/models/sequence/ss/standalone/s4.py", line 427, in forward
    C = _r2c(self.C)
RuntimeError: Output 3 of BroadcastBackward is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.`
Any idea how to solve this?

**Comment by albertfgu** [comment]
Sorry for the late response. Could you give more detailed instructions for how to reproduce this? What command are you running, what PyTorch version, etc. Did you modify the script in any way?

**Comment by albertfgu** [comment]
I looked into this in more detail at some point and the culprit was just a `DataParallel` wrapper inside `example.py`. It would have worked with this wrapper removed, and the latest `example.py` script has fixed this.
