### ISSUE TITLE
sashimi generation not working

### ISSUE THREAD

**Issue by 1ucky40nc3** [HazyResearch/state-spaces#68]
I wanted to reproduce your audio/sashimi-sc09 experiment in Google Colaboratory. To do so I created a fork [1ucky40nc3/state-spaces](https://github.com/1ucky40nc3/state-spaces) that migrates the codebase to Python 3.7 and also implements some other things (mixed precision training, 8-bit optimizer). A [colab notebook](https://github.com/1ucky40nc3/state-spaces/blob/main/reproduce.ipynb) I used to reproduce your experiments can also be found in my fork or via the provided link. The experiment config and version info can also be found there, as well as the logs. The training seems to be working fine, aside from the need to reduce the batch size such as in issue #43.

But when I try to generate audio with a given checkpoint I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 242, in _feed
    send_bytes(obj)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
  0% 0/16000 [00:00<?, ?it/s]
Error executing job with overrides: ['experiment=audio/sashimi-sc09', 'trainer.accumulate_grad_batches=8', 'trainer.max_epochs=1000', 'trainer.limit_train_batches=0.1', 'trainer.limit_val_batches=0.1', 'trainer.precision=16', 'loader.batch_size=8', 'loader.drop_last=True', 'loader.num_workers=4', 'optimizer._name_=adamw', 'optimizer.lr=0.001', 'optimizer.weight_decay=0.0', 'dataset.bits=8', 'dataset.quantization=mu-law', 'model.d_model=64', 'model.n_layers=8', 'encoder=embedding', 'checkpoint_path=./outputs/2022-09-24/16-15-51-079206/checkpoints/val/loss.ckpt', 'n_samples=4', 'l_sample=16000']
Traceback (most recent call last):
  File "/content/state-spaces/generate.py", line 236, in main
    config=config,
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/state-spaces/generate.py", line 116, in generate
    probs = probs.squeeze(1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
I'm writing this issue, because I don't find it easy to fix the cause of this error.
I already tried to set the `return_logprobs=False` for the `generate` fundtion in `generate.py`.
This gives me the following error:
```
  0% 1/16000 [00:00<06:22, 41.80it/s]
Error executing job with overrides: ['experiment=audio/sashimi-sc09', 'trainer.accumulate_grad_batches=8', 'trainer.max_epochs=1000', 'trainer.limit_train_batches=0.1', 'trainer.limit_val_batches=0.1', 'trainer.precision=16', 'loader.batch_size=8', 'loader.drop_last=True', 'loader.num_workers=4', 'optimizer._name_=adamw', 'optimizer.lr=0.001', 'optimizer.weight_decay=0.0', 'dataset.bits=8', 'dataset.quantization=mu-law', 'model.d_model=64', 'model.n_layers=8', 'encoder=embedding', 'checkpoint_path=./outputs/2022-09-24/16-15-51-079206/checkpoints/val/loss.ckpt', 'n_samples=4', 'l_sample=16000']
Traceback (most recent call last):
  File "/content/state-spaces/generate.py", line 236, in main
    config=config,
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/state-spaces/generate.py", line 106, in generate
    y_t = Categorical(logits=y_t/tau).sample()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributions/distribution.py", line 56, in __init__
    f"Expected parameter {param} "
ValueError: Expected parameter logits (Tensor of shape (256,)) of distribution Categorical(logits: torch.Size([256])) to satisfy the constraint IndependentConstraint(Real(), 1), but found invalid values:
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       device='cuda:0')

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
Thanks!

**Comment by albertfgu** [comment]
Could you paste the exact training and generation command line that you used?

It looks like a bunch of hyperparameters were passed in, and I wonder if it's possible that an error occurs if the hyperparameters at train/generation time aren't exactly the same.

It looks like you trained the model directly in this repo, which means there should be an easier way to run the generation script that automatically reads the parameters from the experiment log. You should be able to run it like this:

```
python -m generate experiment_path=$PWD/outputs/2022-09-24/16-15-51-079206/
```
(the rest of the generation script parameters have default settings configured for SC09)

This usage is documented here: https://github.com/HazyResearch/state-spaces#example-2-audio (Option 2)


If this still doesn't work, is there anything you modified inside the training code or model?

**Comment by 1ucky40nc3** [comment]
I tested your command:

> `python -m generate experiment_path=$PWD/outputs/2022-09-24/16-15-51-079206/`

And the same error message was produced...
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 111
CUDA SETUP: Loading binary /usr/local/lib/python3.7/dist-packages/bitsandbytes/libbitsandbytes_cuda111.so...
CONFIG
├── train
│   └── seed: 0                                                                 
│       interval: epoch                                                         
│       monitor: val/accuracy                                                   
│       mode: max                                                               
│       ema: 0.0                                                                
│       test: false                                                             
│       debug: false                                                            
│       ignore_warnings: false                                                  
│       state:                                                                  
│         mode: null                                                            
│         n_context: 0                                                          
│         n_context_eval: 0                                                     
│       ckpt: null                                                              
│       disable_dataset: false                                                  
│       validate_at_start: false                                                
│       pretrained_model_path: null                                             
│       pretrained_model_strict_load: true                                      
│       pretrained_model_state_hook:                                            
│         _name_: null                                                          
│       post_init_hook:                                                         
│         _name_: null                                                          
│       layer_decay:                                                            
│         _name_: null                                                          
│         decay: 0.7                                                            
│                                                                               
├── tolerance
│   └── logdir: ./resume                                                        
│       id: null                                                                
│                                                                               
├── wandb
│   └── project: hippo                                                          
│       group: ''                                                               
│       job_type: training                                                      
│       mode: online                                                            
│       save_dir: null                                                          
│       id: null                                                                
│                                                                               
├── trainer
│   └── gpus: 1                                                                 
│       accumulate_grad_batches: 1                                              
│       max_epochs: 200                                                         
│       gradient_clip_val: 0.0                                                  
│       log_every_n_steps: 10                                                   
│       limit_train_batches: 1.0                                                
│       limit_val_batches: 1.0                                                  
│       weights_summary: top                                                    
│       progress_bar_refresh_rate: 1                                            
│       track_grad_norm: -1                                                     
│       precision: 32                                                           
│                                                                               
├── loader
│   └── batch_size: 32                                                          
│       num_workers: 4                                                          
│       pin_memory: true                                                        
│       drop_last: true                                                         
│                                                                               
├── dataset
│   └── _name_: sc09                                                            
│       bits: 8                                                                 
│       quantization: mu-law                                                    
│       pad_len: null                                                           
│                                                                               
├── task
│   └── _name_: base                                                            
│       loss: cross_entropy                                                     
│       metrics:                                                                
│       - bpb                                                                   
│       - accuracy                                                              
│       - accuracy@3                                                            
│       - accuracy@5                                                            
│       - accuracy@10                                                           
│       torchmetrics: null                                                      
│                                                                               
├── optimizer
│   └── _name_: adamw                                                           
│       lr: 0.001                                                               
│       weight_decay: 0.0                                                       
│                                                                               
├── scheduler
│   └── _name_: plateau                                                         
│       mode: max                                                               
│       factor: 0.2                                                             
│       patience: 20                                                            
│       min_lr: 0.0                                                             
│                                                                               
├── encoder
│   └── embedding                                                               
├── decoder
│   └── _name_: sequence                                                        
│       mode: last                                                              
│                                                                               
├── model
│   └── layer:                                                                  
│         _name_: s4                                                            
│         d_state: 64                                                           
│         channels: 1                                                           
│         bidirectional: false                                                  
│         activation: gelu                                                      
│         postact: glu                                                          
│         initializer: null                                                     
│         weight_norm: false                                                    
│         hyper_act: null                                                       
│         gate: null                                                            
│         bottleneck: null                                                      
│         tie_dropout: null                                                     
│         mode: nplr                                                            
│         measure: legs                                                         
│         rank: 1                                                               
│         dt_min: 0.001                                                         
│         dt_max: 0.1                                                           
│         lr:                                                                   
│           dt: 0.001                                                           
│           A: 0.001                                                            
│           B: 0.001                                                            
│         n_ssm: 1                                                              
│         deterministic: false                                                  
│         l_max: null                                                           
│         verbose: true                                                         
│       _name_: sashimi                                                         
│       d_model: 64                                                             
│       n_layers: 8                                                             
│       pool:                                                                   
│       - 4                                                                     
│       - 4                                                                     
│       expand: 2                                                               
│       ff: 2                                                                   
│       prenorm: true                                                           
│       dropout: 0.0                                                            
│       dropres: 0.0                                                            
│       initializer: null                                                       
│       transposed: true                                                        
│       residual: R                                                             
│       norm: layer                                                             
│       interp: 0                                                               
│       act_pool: null                                                          
│                                                                               
├── callbacks
│   └── learning_rate_monitor:                                                  
│         logging_interval: epoch                                               
│       timer:                                                                  
│         step: true                                                            
│         inter_step: false                                                     
│         epoch: true                                                           
│         val: true                                                             
│       params:                                                                 
│         total: true                                                           
│         trainable: true                                                       
│         fixed: true                                                           
│       model_checkpoint:                                                       
│         monitor: val/accuracy                                                 
│         mode: max                                                             
│         save_top_k: 1                                                         
│         save_last: true                                                       
│         dirpath: checkpoints/                                                 
│         filename: val/accuracy                                                
│         auto_insert_metric_name: false                                        
│         verbose: true                                                         
│                                                                               
├── experiment_path
│   └── /content/state-spaces/outputs/2022-09-27/09-56-38-624238                
├── checkpoint_path
│   └── checkpoints/val/loss.ckpt                                               
├── l_sample
│   └── 16000                                                                   
├── n_samples
│   └── 32                                                                      
├── n_batch
│   └── 32                                                                      
├── n_reps
│   └── 1                                                                       
├── l_prefix
│   └── 0                                                                       
├── top_p
│   └── 1.0                                                                     
├── temp
│   └── 1.0                                                                     
├── split
│   └── val                                                                     
├── save_dir
│   └── sashimi/samples                                                         
├── load_data
│   └── True                                                                    
├── decode
│   └── audio                                                                   
├── test_generation
│   └── False                                                                   
└── debug
    └── False                                                                   
Loading model...
Global seed set to 0
[2022-09-27 10:05:22,336][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmpq81c44ld
[2022-09-27 10:05:22,336][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmpq81c44ld/_remote_module_non_scriptable.py
Found a total number of 31158 audio files...
Found a total number of 3643 audio files...
Found a total number of 4107 audio files...
encoder_cfg ['embedding', None]
[2022-09-27 10:05:23,535][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,553][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,565][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,577][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,590][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,601][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,613][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,625][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (256, 64, None)
[2022-09-27 10:05:23,639][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,647][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,655][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,663][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,671][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,825][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,833][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,841][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (128, 64, None)
[2022-09-27 10:05:23,850][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
[2022-09-27 10:05:23,856][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
[2022-09-27 10:05:23,863][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
[2022-09-27 10:05:23,869][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
[2022-09-27 10:05:23,876][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
[2022-09-27 10:05:23,883][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
[2022-09-27 10:05:23,889][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
[2022-09-27 10:05:23,896][src.models.sequence.ss.s4][INFO] - Constructing S4 (H, N, L) = (64, 64, None)
encoder Embedding(256, 64) <class 'torch.nn.modules.sparse.Embedding'>
Custom load_state_dict function is running.
  0% 0/16000 [00:00<?, ?it/s]
Error executing job with overrides: ['experiment_path=/content/state-spaces/outputs/2022-09-27/09-56-38-624238']
Traceback (most recent call last):
  File "/content/state-spaces/generate.py", line 236, in main
    config=config,
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/state-spaces/generate.py", line 116, in generate
    probs = probs.squeeze(1)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
Here is the training command:
```
!python -m train \
    experiment=audio/sashimi-sc09 \
    trainer.accumulate_grad_batches=8 \
    trainer.max_epochs=1 \
    trainer.limit_train_batches=0.1 \
    trainer.limit_val_batches=0.1 \
    trainer.precision=16 \
    loader.batch_size=8 \
    loader.drop_last=True \
    loader.num_workers=4 \
    optimizer._name_="adamw" \
    optimizer.lr=1e-3 \
    optimizer.weight_decay=0.0 \
    dataset.bits=8 \
    dataset.quantization="mu-law" \
    model.d_model=64 \
    model.n_layers=8 \
    encoder="embedding"
```
Moving forward I will look into the changes in my fork.
Thanks for your quick response ;)

**Comment by 1ucky40nc3** [comment]
I wrote a new [hacky colab](https://github.com/1ucky40nc3/state-spaces/blob/main/reproduce_state_space_migration.ipynb). It contains all changes needed to get this repo working in colab and a working training and inference example. The issue therefore lies in my fork. Thanks for your efforts!

**Comment by albertfgu** [comment]
No problem!

In the future, another suggestion I have is to try ablating the flags to see if any of them cause issues. For example, you can train faster with
```
python -m train experiment=audio/sashimi-sc09 model.n_layers=1 trainer.limit_train_batches=10 trainer.limit_val_batches=10 trainer.max_epochs=2
```
which will train a 1-layer model for 2 epochs, limiting to 10 train/validation batches per epoch. This will complete very fast and you can test generation on it. Then you can add back any flags or modifications you've introduced and see if any of them are the culprits.
