### ISSUE TITLE
Training on midi

### ISSUE THREAD

**Issue by ep-oi** [HazyResearch/state-spaces#80]
I want to train a S4 model on midi, which I already have as discrete events. How do I create a dataset with which I can train?

**Comment by ep-oi** [comment]
Btw, I use Colab. When I execute `!python -m train dataset=bell model=s4` I get the error:
```
Global seed set to 0
[2022-12-12 22:17:23,232][__main__][INFO] - Instantiating callback <pytorch_lightning.callbacks.LearningRateMonitor>
[2022-12-12 22:17:23,232][__main__][INFO] - Instantiating callback <src.callbacks.timer.Timer>
[2022-12-12 22:17:23,233][__main__][INFO] - Instantiating callback <src.callbacks.params.ParamsLog>
[2022-12-12 22:17:23,234][__main__][INFO] - Instantiating callback <pytorch_lightning.callbacks.ModelCheckpoint>
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
[2022-12-12 22:17:23,284][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmp7en0ki4q
[2022-12-12 22:17:23,284][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmp7en0ki4q/_remote_module_non_scriptable.py
Error executing job with overrides: ['dataset=bell', 'model=s4']
Traceback (most recent call last):
  File "/content/train.py", line 686, in main
    train(config)
  File "/content/train.py", line 657, in train
    model = SequenceLightningModule(config)
  File "/content/train.py", line 137, in __init__
    self.dataset = SequenceDataset.registry[self.hparams.dataset._name_](
KeyError: 'bell'
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
#
bell.py:
```
import numpy as np
import torch
import torchvision
from einops.layers.torch import Rearrange
from src.utils import permutations

from src.dataloaders.base import default_data_path, ImageResolutionSequenceDataset, ResolutionSequenceDataset, SequenceDataset


class CSVMIDI(SequenceDataset):
    _name_ = "csvmidi"

    @property
    def init_defaults(self):
        return {
            "permute": True,
            "val_split": 0.1,
            "seed": 42,  # For train/val split
        }

    def setup(self):
        self.data_dir = '/content/csv'
```
 #
bell.yaml:
```
_name_: bell
permute: True
val_split: 0.1
seed: 42
```

I just tried to create my own dataset and got stuck here.

**Comment by ep-oi** [comment]
I got this to work. However `!python -m generate dataset=bell checkpoint_path=/content/outputs/2022-12-14/23-40-07-965990/checkpoints/loss.ckpt` raises a problem:
```
File "/content/generate.py", line 222, in main
    batch = (x.repeat(config.n_reps, 1), None, None)
RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor
```

**Comment by albertfgu** [comment]
It looks like the data doesn't have the shape that the generate script expects. Try running one of the documented examples and setting a breakpoint to check the shapes.

**Comment by albertfgu** [comment]
By the way, I'll note that MIDI is a data format that I think S4 will have a hard time on. In general I think CNNs struggle with data that is not time-invariant, especially "event-encoded" data like MIDI.
